---
title: "EDA_A_Romanov"
output: html_document
date: "2023-05-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Requiered packages:
```{r, message=FALSE}
#load packages
library(dplyr)
library(readxl)
library(ggplot2)
library(maps)
library(caret)
library(tree)

```

## Loading data + Fish species per country

```{r}
class <-read.csv("data/class.csv")
index <- read.csv("data/index.csv")
zoo1 <- read_excel("data/zoo1.xlsx")
zoo2 <- read.csv("data/zoo2.csv")
zoo3 <- read.csv("data/zoo3.csv")

dim(index)
glimpse(zoo1)
is.na(class)

fish <- select(index, c("IUCN", "Species", "Country", "Value")) %>%
  filter(Species == "Fish", IUCN == "TOT_KNOWN") %>%
  select(Country, Value)

fish_plot <- ggplot(data = fish, aes(x = Country, y = Value)) + 
  geom_bar(stat = "identity") +
  xlab("Country") +
  ylab("Value") +
  ggtitle("Value of fish species") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, margin = margin(t = 10)))

print(fish_plot)
```

## Vulnerable species in Germany



```{r}
#Number of vulnerable species in Germany

endangered_ger <- select(index, c("IUCN", "Species", "COU", "Value")) %>%
  filter(IUCN=="VULNERABLE", COU == "DEU") %>%
  select(Species, Value)

endangered_ger <- select(index, c("IUCN", "Species", "COU", "Value")) %>%
  filter(IUCN=="VULNERABLE", COU == "DEU") %>%
  select(Species, Value)

endangered_ger_plot <- ggplot(data = endangered_ger, aes(x = Species, y = Value)) +
  geom_bar(stat = "identity") +
  xlab("Species") + 
  ylab("Value") +
  ggtitle("Value of endangered species in germany") + 
  theme(axis.title.x = element_text(angle = 0, hjust = 1, margin = margin(t = 10)))

print(endangered_ger_plot)
```

## Vulnerable species in Germany without Invertebrates

```{r}
#Number of endangered species in Germany without invertebrates

#wo = without
endangered_ger_wo_invertebrates <- slice_head(endangered_ger,n = 5)

endangered_ger_wo_invertebrates_plot <- ggplot(data = endangered_ger_wo_invertebrates, 
                                               aes(x = Species, y = Value))+
  geom_bar(stat = "identity") +
  xlab("Species") + 
  ylab("Value") +
  ggtitle("Value of endangered species without invertebrates in germany") + 
  theme(axis.title.x = element_text(angle = 0, hjust = 1, margin = margin(t = 10)))

print(endangered_ger_wo_invertebrates_plot)
```


## Merging Data
```{r}
zoo1_temp <- zoo1
not_change <- c("animal_name", "legs", "class_type") # these columns should not be changed

# this took me way to much time lol
for (i in 1:ncol(zoo1_temp)) {
  if (names(zoo1_temp)[i] %in% not_change){
    next
  }
  else {
    zoo1_temp[i] <- lapply(zoo1_temp[i], as.logical)
    class(zoo1_temp[i])
  }
}

zoo2_temp <- zoo2

for (i in 1:ncol(zoo2_temp)) {
  if (names(zoo2_temp)[i] %in% not_change){
    next
  }
  else {
    zoo2_temp[i] <- lapply(zoo2_temp[i], as.logical)
    class(zoo2_temp[i])
  }
}

zoo3_temp <- zoo3

for (i in 1:ncol(zoo3_temp)) {
  if (names(zoo3_temp)[i] %in% not_change){
    next
  }
  else {
    zoo3_temp[i] <- lapply(zoo3_temp[i], as.logical)
    class(zoo3_temp[i])
  }
}

zoo_complete <- bind_rows(zoo1_temp, zoo2_temp, zoo3_temp)

# select necessary columns
class_selection <- select(class, c("Class_Number", "Class_Type")) %>%
  rename(class_type = Class_Number)
zoo_dataset <- inner_join(zoo_complete, class_selection, by = "class_type")

```
## Map of endangered species by value
```{r}
world_map <- map_data("world")
# get critical endangered mammals
endangered_world <- select(index, "IUCN", "SPEC", "Country", "Value") %>%
  filter(IUCN == "CRITICAL", SPEC == "MAMMAL") %>%
  select(Country, Value)

#change country names so they will be displayed
endangered_world[19, "Country"] <- "Slovakia"
endangered_world[23, "Country"] <- "Turkey"
endangered_world[24, "Country"] <- "UK"

#rename column for join
colnames(endangered_world)[1] <- "region"

# merge data

#endangered_world_map <- merge(world_map, endangered_world, by.x = "region", by.y = "Country", all.x = TRUE) OLD

endangered_world_map <- inner_join(world_map, endangered_world, by = "region")

ggplot() +
  geom_polygon(data = endangered_world_map, aes(x = long, y = lat, group = group, fill = Value)) +
  scale_fill_gradient(low = "lightpink", high = "darkred") +
  geom_path(data = world_map, aes(x = long, y = lat, group = group), color = "darkgrey", linewidth = 0.1) +
  theme(panel.background = element_rect(fill="white")) + 
  labs(fill = "Number of \nendangered mammals:") +
  coord_equal()
```

## Naive Classification Tree
```{r}
zoo_partition <- createDataPartition(zoo_dataset$class_type, p = 0.7, list = FALSE)
zoo_training <- zoo_dataset[zoo_partition,]
zoo_test <- zoo_dataset[-zoo_partition,]

my_tree <- tree(factor(zoo_training$Class_Type) ~ .-animal_name-Class_Type-class_type, data = zoo_training)
plot(my_tree, 
     main = "Zoo decision tree", 
     type = "uniform")
text(my_tree)
```
























